# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 07:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new', models.BooleanField(default=True)),
                ('profilePic', models.URLField(default='http://www.adtechnology.co.uk/images/UGM-default-user.png')),
                ('link', models.URLField(default='https://www.facebook.com/DonaldTrump/?fref=ts')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('feedback', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('university', models.CharField(max_length=100, null=True)),
                ('course', models.CharField(max_length=200, null=True)),
                ('year', models.PositiveIntegerField(default=0, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('matricId', models.CharField(max_length=20, null=True)),
                ('school', models.CharField(max_length=100, null=True)),
                ('rating', models.PositiveIntegerField(default=3, null=True)),
                ('account_number', models.CharField(max_length=40, null=True)),
                ('account_holder_name', models.CharField(max_length=60, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_title', models.CharField(max_length=200, null=True)),
                ('txnid', models.CharField(max_length=200, null=True)),
                ('invoice', models.CharField(max_length=200, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('paid', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('tagline', models.TextField(null=True)),
                ('overview', models.TextField(null=True)),
                ('picture', models.ImageField(upload_to='trips')),
                ('itinerary', models.TextField(null=True)),
                ('date', models.DateField(help_text='Date of the Trip', null=True)),
                ('startTime', models.TimeField(help_text='Start time of trip', null=True)),
                ('endTime', models.TimeField(help_text='End time of trip', null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('minGroupSize', models.PositiveIntegerField(default=0, null=True)),
                ('maxGroupSize', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.FloatField(null=True)),
                ('includes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=10)),
                ('excludes', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=10)),
                ('transportation', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=20)),
                ('custs', models.ManyToManyField(default='', related_name='Customers', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Host', to=settings.AUTH_USER_MODEL)),
                ('theme', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='TripBuddy.Theme')),
            ],
            options={
                'permissions': (('add_trips', 'Can add trips to the database'), ('delete_trips', 'Can delete trips from the database')),
            },
        ),
    ]
