# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 09:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TripBuddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='itemsList',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), null=True, size=10),
        ),
    ]
